### ISSUE TITLE
typo in "over" composition function

### ISSUE THREAD

**Issue by leddoo** [jrmuizel/sw-composite#13]
this is the line in question: https://github.com/jrmuizel/sw-composite/blob/7babc88317714bb5aacefdd9251b541863c800ae/src/lib.rs#L803

it should be:
```rust
src + ((rb & mask) | (ag & !mask))
```
cause `+` binds stronger than `|`.

here's what the issue looks like in practice:
left: the current version.
right: the fixed version.
![image](https://user-images.githubusercontent.com/42097768/226115682-366473f2-2b0a-4140-be10-bdd48f72dfc2.png)

**Comment by jrmuizel** [comment]
Thanks for finding this. I'm surprised I never noticed it before.
